// Minecraft Recipe Database
// Format: { "Item Name": { in: { "Ingredient": count, ... }, out: count }, ... }
// Items not in this list are treated as raw materials.

const RECIPES = {
  // === WOOD ===
  "Oak Planks": { in: {"Oak Log":1}, out:4 },
  "Spruce Planks": { in: {"Spruce Log":1}, out:4 },
  "Birch Planks": { in: {"Birch Log":1}, out:4 },
  "Jungle Planks": { in: {"Jungle Log":1}, out:4 },
  "Acacia Planks": { in: {"Acacia Log":1}, out:4 },
  "Dark Oak Planks": { in: {"Dark Oak Log":1}, out:4 },
  "Mangrove Planks": { in: {"Mangrove Log":1}, out:4 },
  "Cherry Planks": { in: {"Cherry Log":1}, out:4 },
  "Crimson Planks": { in: {"Crimson Stem":1}, out:4 },
  "Warped Planks": { in: {"Warped Stem":1}, out:4 },
  "Bamboo Planks": { in: {"Bamboo Block":1}, out:2 },
  "Bamboo Block": { in: {"Bamboo":9}, out:1 },
  "Sticks": { in: {"Planks":2}, out:4 },
  "Planks": { in: {"Log":1}, out:4 },

  // === BASIC WOOD ITEMS ===
  "Crafting Table": { in: {"Planks":4}, out:1 },
  "Chest": { in: {"Planks":8}, out:1 },
  "Barrel": { in: {"Planks":6,"Wooden Slab":2}, out:1 },
  "Wooden Slab": { in: {"Planks":3}, out:6 },
  "Wooden Stairs": { in: {"Planks":6}, out:4 },
  "Wooden Door": { in: {"Planks":6}, out:3 },
  "Wooden Trapdoor": { in: {"Planks":6}, out:2 },
  "Fence": { in: {"Planks":4,"Sticks":2}, out:3 },
  "Fence Gate": { in: {"Planks":2,"Sticks":4}, out:1 },
  "Sign": { in: {"Planks":6,"Sticks":1}, out:3 },
  "Hanging Sign": { in: {"Stripped Log":2,"Chain":2}, out:6 },
  "Chain": { in: {"Iron Nugget":2,"Iron Ingot":1}, out:1 },
  "Ladder": { in: {"Sticks":7}, out:3 },
  "Bowl": { in: {"Planks":3}, out:4 },
  "Wooden Button": { in: {"Planks":1}, out:1 },
  "Wooden Pressure Plate": { in: {"Planks":2}, out:1 },
  "Boat": { in: {"Planks":5}, out:1 },
  "Bookshelf": { in: {"Planks":6,"Book":3}, out:1 },
  "Chiseled Bookshelf": { in: {"Planks":6,"Wooden Slab":3}, out:1 },
  "Bed": { in: {"Planks":3,"Wool":3}, out:1 },
  "Painting": { in: {"Sticks":8,"Wool":1}, out:1 },
  "Item Frame": { in: {"Sticks":8,"Leather":1}, out:1 },
  "Armor Stand": { in: {"Sticks":6,"Stone Slab":1}, out:1 },
  "Campfire": { in: {"Sticks":3,"Coal":1,"Log":3}, out:1 },
  "Soul Campfire": { in: {"Sticks":3,"Soul Sand":1,"Log":3}, out:1 },
  "Loom": { in: {"String":2,"Planks":2}, out:1 },
  "Composter": { in: {"Wooden Slab":7}, out:1 },
  "Note Block": { in: {"Planks":8,"Redstone Dust":1}, out:1 },
  "Jukebox": { in: {"Planks":8,"Diamond":1}, out:1 },

  // === TOOLS ===
  "Wooden Pickaxe": { in: {"Planks":3,"Sticks":2}, out:1 },
  "Wooden Axe": { in: {"Planks":3,"Sticks":2}, out:1 },
  "Wooden Shovel": { in: {"Planks":1,"Sticks":2}, out:1 },
  "Wooden Hoe": { in: {"Planks":2,"Sticks":2}, out:1 },
  "Wooden Sword": { in: {"Planks":2,"Sticks":1}, out:1 },
  "Stone Pickaxe": { in: {"Cobblestone":3,"Sticks":2}, out:1 },
  "Stone Axe": { in: {"Cobblestone":3,"Sticks":2}, out:1 },
  "Stone Shovel": { in: {"Cobblestone":1,"Sticks":2}, out:1 },
  "Stone Hoe": { in: {"Cobblestone":2,"Sticks":2}, out:1 },
  "Stone Sword": { in: {"Cobblestone":2,"Sticks":1}, out:1 },
  "Iron Pickaxe": { in: {"Iron Ingot":3,"Sticks":2}, out:1 },
  "Iron Axe": { in: {"Iron Ingot":3,"Sticks":2}, out:1 },
  "Iron Shovel": { in: {"Iron Ingot":1,"Sticks":2}, out:1 },
  "Iron Hoe": { in: {"Iron Ingot":2,"Sticks":2}, out:1 },
  "Iron Sword": { in: {"Iron Ingot":2,"Sticks":1}, out:1 },
  "Gold Pickaxe": { in: {"Gold Ingot":3,"Sticks":2}, out:1 },
  "Gold Axe": { in: {"Gold Ingot":3,"Sticks":2}, out:1 },
  "Gold Shovel": { in: {"Gold Ingot":1,"Sticks":2}, out:1 },
  "Gold Hoe": { in: {"Gold Ingot":2,"Sticks":2}, out:1 },
  "Gold Sword": { in: {"Gold Ingot":2,"Sticks":1}, out:1 },
  "Diamond Pickaxe": { in: {"Diamond":3,"Sticks":2}, out:1 },
  "Diamond Axe": { in: {"Diamond":3,"Sticks":2}, out:1 },
  "Diamond Shovel": { in: {"Diamond":1,"Sticks":2}, out:1 },
  "Diamond Hoe": { in: {"Diamond":2,"Sticks":2}, out:1 },
  "Diamond Sword": { in: {"Diamond":2,"Sticks":1}, out:1 },
  "Netherite Pickaxe": { in: {"Diamond Pickaxe":1,"Netherite Ingot":1}, out:1 },
  "Netherite Axe": { in: {"Diamond Axe":1,"Netherite Ingot":1}, out:1 },
  "Netherite Shovel": { in: {"Diamond Shovel":1,"Netherite Ingot":1}, out:1 },
  "Netherite Hoe": { in: {"Diamond Hoe":1,"Netherite Ingot":1}, out:1 },
  "Netherite Sword": { in: {"Diamond Sword":1,"Netherite Ingot":1}, out:1 },

  // === ARMOR ===
  "Iron Helmet": { in: {"Iron Ingot":5}, out:1 },
  "Iron Chestplate": { in: {"Iron Ingot":8}, out:1 },
  "Iron Leggings": { in: {"Iron Ingot":7}, out:1 },
  "Iron Boots": { in: {"Iron Ingot":4}, out:1 },
  "Gold Helmet": { in: {"Gold Ingot":5}, out:1 },
  "Gold Chestplate": { in: {"Gold Ingot":8}, out:1 },
  "Gold Leggings": { in: {"Gold Ingot":7}, out:1 },
  "Gold Boots": { in: {"Gold Ingot":4}, out:1 },
  "Diamond Helmet": { in: {"Diamond":5}, out:1 },
  "Diamond Chestplate": { in: {"Diamond":8}, out:1 },
  "Diamond Leggings": { in: {"Diamond":7}, out:1 },
  "Diamond Boots": { in: {"Diamond":4}, out:1 },
  "Netherite Helmet": { in: {"Diamond Helmet":1,"Netherite Ingot":1}, out:1 },
  "Netherite Chestplate": { in: {"Diamond Chestplate":1,"Netherite Ingot":1}, out:1 },
  "Netherite Leggings": { in: {"Diamond Leggings":1,"Netherite Ingot":1}, out:1 },
  "Netherite Boots": { in: {"Diamond Boots":1,"Netherite Ingot":1}, out:1 },
  "Shield": { in: {"Planks":6,"Iron Ingot":1}, out:1 },
  "Turtle Shell": { in: {"Scute":5}, out:1 },

  // === MINERAL BLOCKS ===
  "Iron Block": { in: {"Iron Ingot":9}, out:1 },
  "Gold Block": { in: {"Gold Ingot":9}, out:1 },
  "Diamond Block": { in: {"Diamond":9}, out:1 },
  "Emerald Block": { in: {"Emerald":9}, out:1 },
  "Lapis Block": { in: {"Lapis Lazuli":9}, out:1 },
  "Redstone Block": { in: {"Redstone Dust":9}, out:1 },
  "Coal Block": { in: {"Coal":9}, out:1 },
  "Copper Block": { in: {"Copper Ingot":9}, out:1 },
  "Netherite Block": { in: {"Netherite Ingot":9}, out:1 },
  "Raw Iron Block": { in: {"Raw Iron":9}, out:1 },
  "Raw Gold Block": { in: {"Raw Gold":9}, out:1 },
  "Raw Copper Block": { in: {"Raw Copper":9}, out:1 },
  "Iron Nugget": { in: {"Iron Ingot":1}, out:9 },
  "Gold Nugget": { in: {"Gold Ingot":1}, out:9 },
  "Netherite Ingot": { in: {"Netherite Scrap":4,"Gold Ingot":4}, out:1 },

  // === STONE / BUILDING ===
  "Furnace": { in: {"Cobblestone":8}, out:1 },
  "Stone Bricks": { in: {"Stone":4}, out:4 },
  "Stone Brick Slab": { in: {"Stone Bricks":3}, out:6 },
  "Stone Brick Stairs": { in: {"Stone Bricks":6}, out:4 },
  "Stone Brick Wall": { in: {"Stone Bricks":6}, out:6 },
  "Stone Slab": { in: {"Stone":3}, out:6 },
  "Stone Stairs": { in: {"Stone":6}, out:4 },
  "Cobblestone Slab": { in: {"Cobblestone":3}, out:6 },
  "Cobblestone Stairs": { in: {"Cobblestone":6}, out:4 },
  "Cobblestone Wall": { in: {"Cobblestone":6}, out:6 },
  "Brick Block": { in: {"Brick":4}, out:1 },
  "Brick Slab": { in: {"Brick Block":3}, out:6 },
  "Brick Stairs": { in: {"Brick Block":6}, out:4 },
  "Brick Wall": { in: {"Brick Block":6}, out:6 },
  "Nether Brick Block": { in: {"Nether Brick":4}, out:1 },
  "Nether Brick Slab": { in: {"Nether Brick Block":3}, out:6 },
  "Nether Brick Stairs": { in: {"Nether Brick Block":6}, out:4 },
  "Nether Brick Wall": { in: {"Nether Brick Block":6}, out:6 },
  "Nether Brick Fence": { in: {"Nether Brick Block":4,"Nether Brick":2}, out:6 },
  "Red Nether Bricks": { in: {"Nether Wart":2,"Nether Brick":2}, out:1 },
  "Quartz Block": { in: {"Nether Quartz":4}, out:1 },
  "Quartz Slab": { in: {"Quartz Block":3}, out:6 },
  "Quartz Stairs": { in: {"Quartz Block":6}, out:4 },
  "Quartz Pillar": { in: {"Quartz Block":2}, out:2 },
  "Chiseled Quartz": { in: {"Quartz Slab":2}, out:1 },
  "Smooth Quartz": { in: {"Quartz Block":1}, out:1 }, // smelting
  "Sandstone": { in: {"Sand":4}, out:1 },
  "Sandstone Slab": { in: {"Sandstone":3}, out:6 },
  "Sandstone Stairs": { in: {"Sandstone":6}, out:4 },
  "Sandstone Wall": { in: {"Sandstone":6}, out:6 },
  "Cut Sandstone": { in: {"Sandstone":4}, out:4 },
  "Chiseled Sandstone": { in: {"Sandstone Slab":2}, out:1 },
  "Red Sandstone": { in: {"Red Sand":4}, out:1 },
  "Red Sandstone Slab": { in: {"Red Sandstone":3}, out:6 },
  "Red Sandstone Stairs": { in: {"Red Sandstone":6}, out:4 },
  "Polished Granite": { in: {"Granite":4}, out:4 },
  "Polished Diorite": { in: {"Diorite":4}, out:4 },
  "Polished Andesite": { in: {"Andesite":4}, out:4 },
  "Granite": { in: {"Diorite":1,"Nether Quartz":1}, out:1 },
  "Diorite": { in: {"Cobblestone":2,"Nether Quartz":2}, out:2 },
  "Andesite": { in: {"Diorite":1,"Cobblestone":1}, out:2 },
  "Mossy Cobblestone": { in: {"Cobblestone":1,"Vine":1}, out:1 },
  "Mossy Stone Bricks": { in: {"Stone Bricks":1,"Vine":1}, out:1 },
  "Smooth Stone": { in: {"Stone":1}, out:1 }, // smelting
  "Stone": { in: {"Cobblestone":1}, out:1 }, // smelting
  "Deepslate Bricks": { in: {"Polished Deepslate":4}, out:4 },
  "Polished Deepslate": { in: {"Cobbled Deepslate":4}, out:4 },
  "Deepslate Tiles": { in: {"Deepslate Bricks":4}, out:4 },
  "Mud Bricks": { in: {"Packed Mud":4}, out:4 },
  "Packed Mud": { in: {"Mud":1,"Wheat":1}, out:1 },
  "Prismarine": { in: {"Prismarine Shard":4}, out:1 },
  "Prismarine Bricks": { in: {"Prismarine Shard":9}, out:1 },
  "Dark Prismarine": { in: {"Prismarine Shard":8,"Ink Sac":1}, out:1 },
  "Sea Lantern": { in: {"Prismarine Shard":4,"Prismarine Crystals":5}, out:1 },
  "Purpur Block": { in: {"Popped Chorus Fruit":4}, out:4 },
  "Purpur Pillar": { in: {"Purpur Slab":2}, out:1 },
  "Purpur Slab": { in: {"Purpur Block":3}, out:6 },
  "Purpur Stairs": { in: {"Purpur Block":6}, out:4 },
  "End Stone Bricks": { in: {"End Stone":4}, out:4 },
  "Blackstone Slab": { in: {"Blackstone":3}, out:6 },
  "Blackstone Stairs": { in: {"Blackstone":6}, out:4 },
  "Blackstone Wall": { in: {"Blackstone":6}, out:6 },
  "Polished Blackstone": { in: {"Blackstone":4}, out:4 },
  "Polished Blackstone Bricks": { in: {"Polished Blackstone":4}, out:4 },
  "Cut Copper": { in: {"Copper Block":4}, out:4 },
  "Cut Copper Slab": { in: {"Cut Copper":3}, out:6 },
  "Cut Copper Stairs": { in: {"Cut Copper":6}, out:4 },
  "Tuff Bricks": { in: {"Polished Tuff":4}, out:4 },
  "Polished Tuff": { in: {"Tuff":4}, out:4 },

  // === GLASS ===
  "Glass": { in: {"Sand":1}, out:1 }, // smelting
  "Glass Pane": { in: {"Glass":6}, out:16 },
  "Tinted Glass": { in: {"Glass":1,"Amethyst Shard":4}, out:2 },

  // === CONCRETE ===
  "White Concrete Powder": { in: {"Sand":4,"Gravel":4,"White Dye":1}, out:8 },
  "Black Concrete Powder": { in: {"Sand":4,"Gravel":4,"Black Dye":1}, out:8 },
  "Red Concrete Powder": { in: {"Sand":4,"Gravel":4,"Red Dye":1}, out:8 },
  "Blue Concrete Powder": { in: {"Sand":4,"Gravel":4,"Blue Dye":1}, out:8 },
  "Green Concrete Powder": { in: {"Sand":4,"Gravel":4,"Green Dye":1}, out:8 },
  "Yellow Concrete Powder": { in: {"Sand":4,"Gravel":4,"Yellow Dye":1}, out:8 },
  "Orange Concrete Powder": { in: {"Sand":4,"Gravel":4,"Orange Dye":1}, out:8 },
  "Purple Concrete Powder": { in: {"Sand":4,"Gravel":4,"Purple Dye":1}, out:8 },
  "Cyan Concrete Powder": { in: {"Sand":4,"Gravel":4,"Cyan Dye":1}, out:8 },
  "Light Blue Concrete Powder": { in: {"Sand":4,"Gravel":4,"Light Blue Dye":1}, out:8 },
  "Lime Concrete Powder": { in: {"Sand":4,"Gravel":4,"Lime Dye":1}, out:8 },
  "Magenta Concrete Powder": { in: {"Sand":4,"Gravel":4,"Magenta Dye":1}, out:8 },
  "Pink Concrete Powder": { in: {"Sand":4,"Gravel":4,"Pink Dye":1}, out:8 },
  "Gray Concrete Powder": { in: {"Sand":4,"Gravel":4,"Gray Dye":1}, out:8 },
  "Light Gray Concrete Powder": { in: {"Sand":4,"Gravel":4,"Light Gray Dye":1}, out:8 },
  "Brown Concrete Powder": { in: {"Sand":4,"Gravel":4,"Brown Dye":1}, out:8 },

  // === TERRACOTTA ===
  "Terracotta": { in: {"Clay Ball":4}, out:1 }, // smelting clay block, simplified

  // === REDSTONE ===
  "Redstone Torch": { in: {"Sticks":1,"Redstone Dust":1}, out:1 },
  "Repeater": { in: {"Stone":3,"Redstone Torch":2,"Redstone Dust":1}, out:1 },
  "Comparator": { in: {"Stone":3,"Redstone Torch":3,"Nether Quartz":1}, out:1 },
  "Piston": { in: {"Planks":3,"Cobblestone":4,"Iron Ingot":1,"Redstone Dust":1}, out:1 },
  "Sticky Piston": { in: {"Piston":1,"Slime Ball":1}, out:1 },
  "Observer": { in: {"Cobblestone":6,"Redstone Dust":2,"Nether Quartz":1}, out:1 },
  "Dropper": { in: {"Cobblestone":7,"Redstone Dust":1}, out:1 },
  "Dispenser": { in: {"Cobblestone":7,"Bow":1,"Redstone Dust":1}, out:1 },
  "Bow": { in: {"Sticks":3,"String":3}, out:1 },
  "Crossbow": { in: {"Sticks":3,"Iron Ingot":1,"String":2,"Tripwire Hook":1}, out:1 },
  "Hopper": { in: {"Iron Ingot":5,"Chest":1}, out:1 },
  "Lever": { in: {"Sticks":1,"Cobblestone":1}, out:1 },
  "Tripwire Hook": { in: {"Iron Ingot":1,"Sticks":1,"Planks":1}, out:2 },
  "Trapped Chest": { in: {"Chest":1,"Tripwire Hook":1}, out:1 },
  "Daylight Detector": { in: {"Glass":3,"Nether Quartz":3,"Wooden Slab":3}, out:1 },
  "Target": { in: {"Redstone Dust":4,"Hay Bale":1}, out:1 },
  "Hay Bale": { in: {"Wheat":9}, out:1 },
  "TNT": { in: {"Gunpowder":5,"Sand":4}, out:1 },
  "Redstone Lamp": { in: {"Redstone Dust":4,"Glowstone":1}, out:1 },
  "Glowstone": { in: {"Glowstone Dust":4}, out:1 },
  "Stone Pressure Plate": { in: {"Stone":2}, out:1 },

  // === RAILS ===
  "Rail": { in: {"Iron Ingot":6,"Sticks":1}, out:16 },
  "Powered Rail": { in: {"Gold Ingot":6,"Sticks":1,"Redstone Dust":1}, out:6 },
  "Detector Rail": { in: {"Iron Ingot":6,"Stone Pressure Plate":1,"Redstone Dust":1}, out:6 },
  "Activator Rail": { in: {"Iron Ingot":6,"Sticks":2,"Redstone Torch":1}, out:6 },
  "Minecart": { in: {"Iron Ingot":5}, out:1 },
  "Chest Minecart": { in: {"Chest":1,"Minecart":1}, out:1 },
  "Hopper Minecart": { in: {"Hopper":1,"Minecart":1}, out:1 },
  "TNT Minecart": { in: {"TNT":1,"Minecart":1}, out:1 },

  // === LIGHTING / MISC ===
  "Torch": { in: {"Coal":1,"Sticks":1}, out:4 },
  "Soul Torch": { in: {"Coal":1,"Sticks":1,"Soul Sand":1}, out:4 },
  "Lantern": { in: {"Iron Nugget":8,"Torch":1}, out:1 },
  "Soul Lantern": { in: {"Iron Nugget":8,"Soul Torch":1}, out:1 },
  "Candle": { in: {"String":1,"Honeycomb":1}, out:1 },
  "Jack o'Lantern": { in: {"Carved Pumpkin":1,"Torch":1}, out:1 },
  "End Rod": { in: {"Blaze Rod":1,"Popped Chorus Fruit":1}, out:4 },

  // === UTILITY BLOCKS ===
  "Anvil": { in: {"Iron Block":3,"Iron Ingot":4}, out:1 },
  "Enchanting Table": { in: {"Book":1,"Diamond":2,"Obsidian":4}, out:1 },
  "Brewing Stand": { in: {"Blaze Rod":1,"Cobblestone":3}, out:1 },
  "Cauldron": { in: {"Iron Ingot":7}, out:1 },
  "Blast Furnace": { in: {"Iron Ingot":5,"Furnace":1,"Smooth Stone":3}, out:1 },
  "Smoker": { in: {"Furnace":1,"Log":4}, out:1 },
  "Smithing Table": { in: {"Iron Ingot":2,"Planks":4}, out:1 },
  "Cartography Table": { in: {"Paper":2,"Planks":4}, out:1 },
  "Fletching Table": { in: {"Flint":2,"Planks":4}, out:1 },
  "Stonecutter": { in: {"Iron Ingot":1,"Stone":3}, out:1 },
  "Grindstone": { in: {"Sticks":2,"Stone Slab":1,"Planks":2}, out:1 },
  "Lectern": { in: {"Wooden Slab":4,"Bookshelf":1}, out:1 },
  "Beacon": { in: {"Obsidian":3,"Glass":5,"Nether Star":1}, out:1 },
  "Conduit": { in: {"Nautilus Shell":8,"Heart of the Sea":1}, out:1 },
  "Respawn Anchor": { in: {"Crying Obsidian":6,"Glowstone":3}, out:1 },
  "Lodestone": { in: {"Chiseled Stone Bricks":8,"Netherite Ingot":1}, out:1 },
  "Chiseled Stone Bricks": { in: {"Stone Brick Slab":2}, out:1 },
  "End Crystal": { in: {"Glass":7,"Eye of Ender":1,"Ghast Tear":1}, out:1 },
  "Eye of Ender": { in: {"Ender Pearl":1,"Blaze Powder":1}, out:1 },
  "Blaze Powder": { in: {"Blaze Rod":1}, out:2 },
  "Ender Chest": { in: {"Obsidian":8,"Eye of Ender":1}, out:1 },

  // === FOOD ===
  "Bread": { in: {"Wheat":3}, out:1 },
  "Cookie": { in: {"Wheat":2,"Cocoa Beans":1}, out:8 },
  "Cake": { in: {"Wheat":3,"Sugar":2,"Egg":1,"Milk Bucket":3}, out:1 },
  "Pumpkin Pie": { in: {"Pumpkin":1,"Sugar":1,"Egg":1}, out:1 },
  "Golden Apple": { in: {"Gold Ingot":8,"Apple":1}, out:1 },
  "Golden Carrot": { in: {"Gold Nugget":8,"Carrot":1}, out:1 },
  "Rabbit Stew": { in: {"Cooked Rabbit":1,"Carrot":1,"Baked Potato":1,"Mushroom":1,"Bowl":1}, out:1 },
  "Mushroom Stew": { in: {"Red Mushroom":1,"Brown Mushroom":1,"Bowl":1}, out:1 },
  "Beetroot Soup": { in: {"Beetroot":6,"Bowl":1}, out:1 },
  "Sugar": { in: {"Sugar Cane":1}, out:1 },

  // === PAPER / BOOKS ===
  "Paper": { in: {"Sugar Cane":3}, out:3 },
  "Book": { in: {"Paper":3,"Leather":1}, out:1 },
  "Book and Quill": { in: {"Book":1,"Ink Sac":1,"Feather":1}, out:1 },
  "Map": { in: {"Paper":8,"Compass":1}, out:1 },
  "Compass": { in: {"Iron Ingot":4,"Redstone Dust":1}, out:1 },
  "Clock": { in: {"Gold Ingot":4,"Redstone Dust":1}, out:1 },
  "Spyglass": { in: {"Amethyst Shard":1,"Copper Ingot":2}, out:1 },
  "Recovery Compass": { in: {"Compass":1,"Echo Shard":8}, out:1 },

  // === SCAFFOLDING ===
  "Scaffolding": { in: {"Bamboo":6,"String":1}, out:6 },

  // === MISCELLANEOUS ===
  "Bucket": { in: {"Iron Ingot":3}, out:1 },
  "Shears": { in: {"Iron Ingot":2}, out:1 },
  "Flint and Steel": { in: {"Iron Ingot":1,"Flint":1}, out:1 },
  "Lead": { in: {"String":4,"Slime Ball":1}, out:2 },
  "Fishing Rod": { in: {"Sticks":3,"String":2}, out:1 },
  "Carrot on a Stick": { in: {"Fishing Rod":1,"Carrot":1}, out:1 },
  "Warped Fungus on a Stick": { in: {"Fishing Rod":1,"Warped Fungus":1}, out:1 },
  "Arrow": { in: {"Flint":1,"Sticks":1,"Feather":1}, out:4 },
  "Spectral Arrow": { in: {"Glowstone Dust":4,"Arrow":1}, out:2 },
  "Flower Pot": { in: {"Brick":3}, out:1 },
  "Banner": { in: {"Wool":6,"Sticks":1}, out:1 },
  "Lightning Rod": { in: {"Copper Ingot":3}, out:1 },
  "Brush": { in: {"Feather":1,"Copper Ingot":1,"Sticks":1}, out:1 },

  // === FIREWORKS ===
  "Firework Rocket": { in: {"Paper":1,"Gunpowder":1}, out:3 },

  // === COPPER VARIANTS ===
  "Copper Grate": { in: {"Copper Block":4}, out:4 },
  "Copper Door": { in: {"Copper Ingot":6}, out:3 },
  "Copper Trapdoor": { in: {"Copper Ingot":4}, out:2 },
  "Copper Bulb": { in: {"Copper Block":1,"Blaze Rod":1,"Redstone Dust":1}, out:4 },

  // === WOOL / CARPET ===
  "White Wool": { in: {"String":4}, out:1 },
  "Carpet": { in: {"Wool":2}, out:3 },
};

// Category tags for UI organization
const CATEGORIES = {
  "Wood": ["Oak Planks","Spruce Planks","Birch Planks","Jungle Planks","Acacia Planks","Dark Oak Planks","Mangrove Planks","Cherry Planks","Crimson Planks","Warped Planks","Bamboo Planks","Bamboo Block","Sticks","Planks","Crafting Table","Chest","Barrel","Wooden Slab","Wooden Stairs","Wooden Door","Wooden Trapdoor","Fence","Fence Gate","Sign","Hanging Sign","Ladder","Bowl","Wooden Button","Wooden Pressure Plate","Boat","Bookshelf","Chiseled Bookshelf","Bed","Painting","Item Frame","Armor Stand","Campfire","Soul Campfire","Loom","Composter","Note Block","Jukebox"],
  "Tools": ["Wooden Pickaxe","Wooden Axe","Wooden Shovel","Wooden Hoe","Wooden Sword","Stone Pickaxe","Stone Axe","Stone Shovel","Stone Hoe","Stone Sword","Iron Pickaxe","Iron Axe","Iron Shovel","Iron Hoe","Iron Sword","Gold Pickaxe","Gold Axe","Gold Shovel","Gold Hoe","Gold Sword","Diamond Pickaxe","Diamond Axe","Diamond Shovel","Diamond Hoe","Diamond Sword","Netherite Pickaxe","Netherite Axe","Netherite Shovel","Netherite Hoe","Netherite Sword","Bucket","Shears","Flint and Steel","Fishing Rod","Bow","Crossbow","Shield","Brush","Spyglass"],
  "Armor": ["Iron Helmet","Iron Chestplate","Iron Leggings","Iron Boots","Gold Helmet","Gold Chestplate","Gold Leggings","Gold Boots","Diamond Helmet","Diamond Chestplate","Diamond Leggings","Diamond Boots","Netherite Helmet","Netherite Chestplate","Netherite Leggings","Netherite Boots","Turtle Shell"],
  "Building": ["Stone Bricks","Stone Brick Slab","Stone Brick Stairs","Stone Brick Wall","Stone Slab","Stone Stairs","Cobblestone Slab","Cobblestone Stairs","Cobblestone Wall","Brick Block","Brick Slab","Brick Stairs","Brick Wall","Nether Brick Block","Nether Brick Slab","Nether Brick Stairs","Nether Brick Wall","Nether Brick Fence","Red Nether Bricks","Quartz Block","Quartz Slab","Quartz Stairs","Quartz Pillar","Chiseled Quartz","Smooth Quartz","Sandstone","Sandstone Slab","Sandstone Stairs","Sandstone Wall","Cut Sandstone","Chiseled Sandstone","Red Sandstone","Red Sandstone Slab","Red Sandstone Stairs","Polished Granite","Polished Diorite","Polished Andesite","Granite","Diorite","Andesite","Mossy Cobblestone","Mossy Stone Bricks","Smooth Stone","Stone","Glass","Glass Pane","Tinted Glass","Deepslate Bricks","Polished Deepslate","Deepslate Tiles","Mud Bricks","Packed Mud","Prismarine","Prismarine Bricks","Dark Prismarine","Sea Lantern","Purpur Block","Purpur Pillar","Purpur Slab","Purpur Stairs","End Stone Bricks","Blackstone Slab","Blackstone Stairs","Blackstone Wall","Polished Blackstone","Polished Blackstone Bricks","Cut Copper","Cut Copper Slab","Cut Copper Stairs","Tuff Bricks","Polished Tuff","Scaffolding","Carpet"],
  "Redstone": ["Redstone Torch","Repeater","Comparator","Piston","Sticky Piston","Observer","Dropper","Dispenser","Hopper","Lever","Tripwire Hook","Trapped Chest","Daylight Detector","Target","TNT","Redstone Lamp","Note Block"],
  "Rails": ["Rail","Powered Rail","Detector Rail","Activator Rail","Minecart","Chest Minecart","Hopper Minecart","TNT Minecart"],
  "Mineral Blocks": ["Iron Block","Gold Block","Diamond Block","Emerald Block","Lapis Block","Redstone Block","Coal Block","Copper Block","Netherite Block","Raw Iron Block","Raw Gold Block","Raw Copper Block"],
  "Utility": ["Furnace","Blast Furnace","Smoker","Anvil","Enchanting Table","Brewing Stand","Cauldron","Smithing Table","Cartography Table","Fletching Table","Stonecutter","Grindstone","Lectern","Beacon","Conduit","Respawn Anchor","Lodestone","Ender Chest"],
  "Combat": ["Arrow","Spectral Arrow","Firework Rocket","Lead"],
  "Food": ["Bread","Cookie","Cake","Pumpkin Pie","Golden Apple","Golden Carrot","Rabbit Stew","Mushroom Stew","Beetroot Soup","Hay Bale"],
  "Lighting": ["Torch","Soul Torch","Lantern","Soul Lantern","Candle","Jack o'Lantern","End Rod","Glowstone","Campfire","Soul Campfire","Redstone Lamp"],
  "Paper & Books": ["Paper","Book","Book and Quill","Map","Compass","Clock","Recovery Compass"],
  "Decoration": ["Painting","Item Frame","Flower Pot","Banner","Armor Stand"],
  "Concrete": ["White Concrete Powder","Black Concrete Powder","Red Concrete Powder","Blue Concrete Powder","Green Concrete Powder","Yellow Concrete Powder","Orange Concrete Powder","Purple Concrete Powder","Cyan Concrete Powder","Light Blue Concrete Powder","Lime Concrete Powder","Magenta Concrete Powder","Pink Concrete Powder","Gray Concrete Powder","Light Gray Concrete Powder","Brown Concrete Powder"],
  "Copper": ["Copper Block","Cut Copper","Cut Copper Slab","Cut Copper Stairs","Copper Grate","Copper Door","Copper Trapdoor","Copper Bulb","Lightning Rod"],
};
